# Generated by Django 4.0.4 on 2022-04-30 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='symptoms',
        ),
    ]
