# Generated by Django 4.0.4 on 2022-04-30 03:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='symptoms',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), size=20), size=None),
        ),
    ]
