# Generated by Django 4.0.4 on 2022-04-30 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status_api', '0002_remove_status_symptoms'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='fears',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='status',
            name='feelings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='status',
            name='troubles',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='status',
            name='worries',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Symptoms',
        ),
    ]
